services:
  - type: web
    name: seatwise-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm run seed && npm start
    envVars:
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_FROM
        value: "SeatWise <devrajsinghal61@gmail.com>"
      - key: BREVO_API_KEY
        sync: false
      - key: PUBLIC_URL
        sync: false
